### ISSUE TITLE
Move docker pull/run commands to a quick-start section

### ISSUE THREAD

**Issue by nuvious** [howsoai/howso-devcontainers#14]
The documentation provides rich information on what the devcontainers are, but the pull command not readily copy-paste-able from the front page README. Recommend making a very short section called 'quickstart' that anyone can copy-paste into their terminal the moment they land on the README.

Will submit a PR for consideration.

**Comment by sdconrox** [comment]
@nuvious Sounds like a great idea. I'll keep an eye out for a PR.

**Comment by nuvious** [comment]
Resolved by #22
